<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.18362.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>0.3.1</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/LazyChromeWindowBridge.Core/LazyChromeWindowBridge.Core.csproj" />
  </ItemGroup>
</Project>
